name: Send Good Morning

on:
  schedule:
    - cron: '30 0 * * *'   # Roz subah 6:00 AM IST (0:30 UTC)
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install instagrapi

      - name: Run Good Morning script
        run: |
          echo "${{ secrets.IG_SESSION }}" | base64 -d > insta_settings.json
          python goodmorning.py
